<?php

namespace khaledBundle\Repository\Entity;

/**
 * ProductMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductMRepository extends \Doctrine\ORM\EntityRepository
{
}
